#!/usr/bin/env bash
set -euo pipefail
PI_DIR="${HOME}/.pi/agent"
CHECKLIST="pi-migration-checklist.md"
ITEMS=(pi-hermes-memory projects-memory sessions skills extensions settings.json models-store.json)

gen_checklist() {
  local f="$1"
  {
    echo "Pi Migration Checklist (auto-generated by pi-agent-backup)"
    echo "Generated: $(date '+%Y-%m-%d %H:%M:%S')"
    echo "NOT PACKAGED — handle manually on the new machine:"
    echo "[1] Login credentials (auth.json excluded)"
    if [ -f "$PI_DIR/auth.json" ]; then
      echo "auth.json on this machine contains credentials for these providers (keys not exported):"
      grep -E '^  "' "$PI_DIR/auth.json" 2>/dev/null | sed -E 's/^  "([^"]+)".*/   - \1/' || echo "   (unparseable)"
      echo "-> New machine: run /login in pi to sign in, or set API key env vars"
    else
      echo "No auth.json found (not logged in)"
    fi
    echo "[2] Skill/extension secret files (*.env excluded)"
    local envs
    envs=$(find "$PI_DIR/skills" "$PI_DIR/extensions" -name ".env*" -not -name "*.example" 2>/dev/null || true)
    if [ -n "$envs" ]; then
      echo "These .env files exist on this machine but were NOT packaged:"
      echo "$envs" | sed "s|$PI_DIR/|   ~/.pi/agent/|"
      echo "-> New machine: copy these files manually or regenerate keys in the service console"
    else
      echo "No .env secret files found"
    fi
    echo "[3] Platform-specific (npm/, bin/ not packaged — recreated by reinstalling pi)"
    echo "   - Skills with local binaries (e.g. vision-tools CLIs) must be reinstalled"
    echo "[4] Machine-local config (not migrated)"
    local proxy
    proxy=$(git config --global --get http.https://github.com.proxy 2>/dev/null || true)
    [ -n "$proxy" ] && echo "   - Detected git proxy: $proxy -> if needed on new machine: git config --global http.https://github.com.proxy $proxy" || echo "   - No git proxy configured"
    echo "PACKAGED:"
    for i in "${ITEMS[@]}"; do [ -e "$PI_DIR/$i" ] && echo "   - $i"; done
  } > "$f"
}

case "${1:-}" in
  backup)
    dest="${2:-${HOME}/pi-agent-backup-$(date +%Y%m%d-%H%M%S).tar.gz}"
    [ -d "$PI_DIR" ] || { echo "ERROR: $PI_DIR not found"; exit 1; }
    self=$(readlink -f "$0" 2>/dev/null || echo "$0")
    tmpd=$(mktemp -d) && gen_checklist "$tmpd/$CHECKLIST" && cp "$self" "$tmpd/pi-agent-backup.sh"
    tar czf "$dest" --exclude=".pi/agent/auth.json" --exclude=".pi/agent/*.env" --exclude=".pi/agent/*.env.*" \
      -C "$HOME" $(for i in "${ITEMS[@]}"; do [ -e "$PI_DIR/$i" ] && echo ".pi/agent/$i"; done) \
      -C "$tmpd" "$CHECKLIST" "pi-agent-backup.sh"
    rm -rf "$tmpd"
    echo "Backup saved: $dest; excluded auth.json & *.env; includes checklist + restore script (self-contained)" ;;
  restore)
    [ -f "${2:-}" ] || { echo "Usage: $0 restore <tar.gz>"; exit 1; }
    mkdir -p "$PI_DIR"
    if [ ! -f "$HOME/pi-agent-backup.sh" ] && tar tzf "$2" | grep -q "^pi-agent-backup.sh$"; then
      tar xzf "$2" -C "$HOME" "pi-agent-backup.sh" && chmod +x "$HOME/pi-agent-backup.sh"
      echo "Restore script extracted from package: $HOME/pi-agent-backup.sh"
    fi
    tar xzf "$2" -C "$HOME"
    rm -f "$PI_DIR/.pi-hermes-locks.sqlite"* 2>/dev/null || true
    echo "Restore complete"
    [ -f "$HOME/$CHECKLIST" ] && { echo "Migration checklist:"; cat "$HOME/$CHECKLIST"; }
    [ -f "$PI_DIR/auth.json" ] && echo "auth.json present" || echo "auth.json missing -> run /login to sign in (expected)"
    [ -d "$PI_DIR/bin" ] && echo "bin/ present" || echo "bin/ missing -> reinstall binary-dependent skills (see checklist [3])"
    echo "Tip: after starting pi, try asking: 'Do you know my work experience?'" ;;
  list) tar tzf "${2:-}" ;;
  *) echo "Usage: $0 {backup [dest] | restore <tar.gz> | list <tar.gz>}"; exit 1 ;;
esac
